include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**.**.dart'
    - 'generated_plugin_registrant.dart'
  errors:
    use_key_in_widget_constructors: ignore

linter:
  rules:
    # Error rules.
    - avoid_dynamic_calls
    - avoid_slow_async_io
    - avoid_type_to_string
    - cancel_subscriptions
    - close_sinks
    - collection_methods_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - prefer_relative_imports
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - use_build_context_synchronously
    # Style rules.
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    - avoid_implementing_value_types
    - avoid_js_rounded_ints
    - avoid_annotating_with_dynamic
    - avoid_redundant_argument_values
    - avoid_positional_boolean_parameters
    - avoid_returning_this
    - avoid_unused_constructor_parameters
    - avoid_types_on_closure_parameters
    - avoid_void_async
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - combinators_ordering
    - conditional_uri_does_not_exist
    - directives_ordering
    - implicit_call_tearoffs
    - join_return_with_assignment
    - missing_whitespace_between_adjacent_strings
    - no_default_cases
    - noop_primitive_operations
    - omit_local_variable_types
    - only_throw_errors
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_constructors_over_static_methods
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_foreach
    - prefer_if_elements_to_conditional_expressions
    - prefer_int_literals
    - prefer_mixin
    - prefer_null_aware_method_calls
    - prefer_single_quotes
    - require_trailing_commas
    - sized_box_shrink_expand
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - sort_child_properties_last
    - tighten_type_of_initializing_formals
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_to_list_in_spreads
    - use_colored_box
    - use_decorated_box
    - use_enums
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_raw_strings
    - use_named_constants
    - use_setters_to_change_properties
    - use_string_buffers
    - use_super_parameters
    - use_test_throws_matchers
    - use_to_and_as_if_applicable
    # Pub rules.
    - secure_pubspec_urls
