targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          class_name_pattern: "Cubit$"