name: test_task
description: Flutter app for interview testing
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  # Localization.
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.0
  # Dependency injection.
  get_it: ^7.6.0

  injectable: ^2.1.2
  # Navigation.

  auto_route: ^7.4.0
  # State management.
  bloc: ^8.1.2

  flutter_bloc: ^8.1.3
  # Union objects.
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

  # Data repository.
  dio: ^5.2.1+1
  retrofit: ^4.0.1


dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.4.5
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.0
  auto_route_generator: ^7.1.1
  freezed: ^2.3.5
  retrofit_generator: ^7.0.1

flutter:
  generate: true

  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-SemiBold.otf
          weight: 700
    - family: custico
      fonts:
        - asset: assets/fonts/custico.ttf

  assets:
    - assets/images/user.jpg